
// argument_distribution automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type ArgumentDistribution struct {
    Total int `json:"total"`
    Path int `json:"path"`
    Query int `json:"query"`
    Header int `json:"header"`
}

