// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import (
	"github.com/apioo/sdkgen-go"
)

type Client struct {
	internal *sdkgen.ClientAbstract
}

func (client *Client) Tag() *TagTag {
	return NewTagTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Star() *StarTag {
	return NewStarTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Trigger() *TriggerTag {
	return NewTriggerTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) PullRequest() *PullRequestTag {
	return NewPullRequestTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Issue() *IssueTag {
	return NewIssueTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Explore() *ExploreTag {
	return NewExploreTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Document() *DocumentTag {
	return NewDocumentTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Commit() *CommitTag {
	return NewCommitTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Authorization() *AuthorizationTag {
	return NewAuthorizationTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Meta() *MetaTag {
	return NewMetaTag(client.internal.HttpClient, client.internal.Parser)
}

func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
	if err != nil {
		return &Client{}, err
	}

	return &Client{
		internal: client,
	}, nil
}

func Build(clientId string, clientSecret string, tokenStore sdkgen.TokenStoreInterface, scopes []string) (*Client, error) {
	var credentials = sdkgen.OAuth2{
		ClientId:         clientId,
		ClientSecret:     clientSecret,
		TokenUrl:         "https://api.typehub.cloud/authorization/token",
		AuthorizationUrl: "",
		TokenStore:       tokenStore,
		Scopes:           scopes,
	}

	return NewClient("https://api.typehub.cloud", credentials)
}
