// comment_reactions automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type CommentReactions struct {
	Like     int `json:"like"`
	Dislike  int `json:"dislike"`
	Laugh    int `json:"laugh"`
	Hooray   int `json:"hooray"`
	Confused int `json:"confused"`
	Heart    int `json:"heart"`
	Rocket   int `json:"rocket"`
	Eyes     int `json:"eyes"`
}
