
// CommitTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    
    "encoding/json"
    "errors"
    "fmt"
    "github.com/apioo/sdkgen-go/v2"
    "io"
    "net/http"
    "net/url"
    
)

type CommitTag struct {
    internal *sdkgen.TagAbstract
}



// Get Returns a commit
func (client *CommitTag) Get(user string, document string, id string) (*Commit, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/commit/:id", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Commit
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// GetAll Returns all commits for a document
func (client *CommitTag) GetAll(user string, document string, startIndex int, count int, search string) (*CommitCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})
    queryParams["startIndex"] = startIndex
    queryParams["count"] = count
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/commit", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data CommitCollection
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewCommitTag(httpClient *http.Client, parser *sdkgen.Parser) *CommitTag {
	return &CommitTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
