
// comment_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type CommentCreate struct {
    Id int `json:"id"`
    User *User `json:"user"`
    Status int `json:"status"`
    Reaction *CommentReactions `json:"reaction"`
    Comment string `json:"comment"`
    UpdateDate string `json:"updateDate"`
    InsertDate string `json:"insertDate"`
}

