// comment_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type CommentCreate struct {
	Id         int              `json:"id"`
	User       User             `json:"user"`
	Status     int              `json:"status"`
	Reaction   CommentReactions `json:"reaction"`
	Comment    string           `json:"comment"`
	UpdateDate time.Time        `json:"updateDate"`
	InsertDate time.Time        `json:"insertDate"`
}
