// document_preview automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type DocumentPreview struct {
	Tags  []Tag    `json:"tags"`
	Types []string `json:"types"`
}
