
// document_meta automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type DocumentMeta struct {
    Description string `json:"description"`
    Private bool `json:"private"`
    BaseVersion string `json:"baseVersion"`
    DevelopmentMode bool `json:"developmentMode"`
    Homepage string `json:"homepage"`
}

