
// DocumentTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    "github.com/apioo/sdkgen-go/v2"
    "io"
    "net/http"
    "net/url"
    
)

type DocumentTag struct {
    internal *sdkgen.TagAbstract
}



// Create Creates a new document
func (client *DocumentTag) Create(user string, payload DocumentCreate) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Delete Removes a document
func (client *DocumentTag) Delete(user string, document string) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("DELETE", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Export Export this document
func (client *DocumentTag) Export(user string, document string, payload DocumentExportRequest) (*DocumentExportResponse, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/export", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data DocumentExportResponse
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Fork Fork this document
func (client *DocumentTag) Fork(user string, document string) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/fork", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Get Returns a document
func (client *DocumentTag) Get(user string, document string, version string) (*Document, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})
    queryParams["version"] = version

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Document
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// GetAll Returns all documents
func (client *DocumentTag) GetAll(user string, startIndex int, count int, search string) (*DocumentCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user

    queryParams := make(map[string]interface{})
    queryParams["startIndex"] = startIndex
    queryParams["count"] = count
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data DocumentCollection
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Import Import a TypeAPI specification to this document
func (client *DocumentTag) Import(user string, document string, payload Passthru) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/import", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Meta Updates the meta data of an document
func (client *DocumentTag) Meta(user string, document string, payload DocumentMeta) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/meta", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PUT", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Reset Resets your document to the latest source
func (client *DocumentTag) Reset(user string, document string, payload Passthru) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/reset", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Revert Reverts your document to this commit
func (client *DocumentTag) Revert(user string, document string, id string, payload Passthru) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/revert/:id", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// ShowPreview Returns a document preview
func (client *DocumentTag) ShowPreview(user string, document string, version string) (*DocumentPreview, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})
    queryParams["version"] = version

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/preview", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data DocumentPreview
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Star Stars this document
func (client *DocumentTag) Star(user string, document string, payload Passthru) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/star", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Update Updates a document
func (client *DocumentTag) Update(user string, document string, payload DocumentUpdate) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PUT", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewDocumentTag(httpClient *http.Client, parser *sdkgen.Parser) *DocumentTag {
	return &DocumentTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
