// document_meta automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type DocumentMeta struct {
	Description string `json:"description"`
	BaseUrl     string `json:"baseUrl"`
	BaseVersion string `json:"baseVersion"`
	Keywords    string `json:"keywords"`
	Homepage    string `json:"homepage"`
	License     string `json:"license"`
}
