// document_export_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type DocumentExportRequest struct {
	Version   string `json:"version"`
	Format    string `json:"format"`
	Namespace string `json:"namespace"`
}
