
// document_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type DocumentCreate struct {
    Name string `json:"name"`
    Description string `json:"description"`
    Private bool `json:"private"`
    BaseVersion string `json:"baseVersion"`
    Homepage string `json:"homepage"`
}

