
// document automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type Document struct {
    Id int `json:"id"`
    User *User `json:"user"`
    Source *Document `json:"source"`
    Status int `json:"status"`
    Stars int `json:"stars"`
    Name string `json:"name"`
    Description string `json:"description"`
    Private bool `json:"private"`
    BaseVersion string `json:"baseVersion"`
    DevelopmentMode bool `json:"developmentMode"`
    Homepage string `json:"homepage"`
    Spec any `json:"spec"`
    UpdateDate string `json:"updateDate"`
    InsertDate string `json:"insertDate"`
}

