
// document_repository automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type DocumentRepository struct {
    Name string `json:"name"`
    Href string `json:"href"`
}

