// document_export_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type DocumentExportResponse struct {
	Href string `json:"href"`
}
