// issue automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type Issue struct {
	Id         int       `json:"id"`
	User       User      `json:"user"`
	Document   Document  `json:"document"`
	Status     int       `json:"status"`
	Title      string    `json:"title"`
	UpdateDate time.Time `json:"updateDate"`
	InsertDate time.Time `json:"insertDate"`
}
