// issue_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type IssueCreate struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}
