
// largest_type automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type LargestType struct {
    Name string `json:"name"`
    PropertyCount int `json:"propertyCount"`
}

