
// method_distribution automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type MethodDistribution struct {
    Get int `json:"get"`
    Post int `json:"post"`
    Put int `json:"put"`
    Delete int `json:"delete"`
    Patch int `json:"patch"`
}

