
// name_count automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type NameCount struct {
    Name string `json:"name"`
    Count int `json:"count"`
}

