
// primitive_type_distribution automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type PrimitiveTypeDistribution struct {
    String int `json:"string"`
    Integer int `json:"integer"`
    Number int `json:"number"`
    Boolean int `json:"boolean"`
    Object int `json:"object"`
    Map int `json:"map"`
    Array int `json:"array"`
    Any int `json:"any"`
    Generic int `json:"generic"`
}

