
// property_bucket automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type PropertyBucket struct {
    Range string `json:"range"`
    Count int `json:"count"`
}

