
// PullRequestTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    "github.com/apioo/sdkgen-go/v2"
    "io"
    "net/http"
    "net/url"
    
)

type PullRequestTag struct {
    internal *sdkgen.TagAbstract
}



// Create Creates a new pull request
func (client *PullRequestTag) Create(user string, document string, payload PullRequestCreate) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/pull_request", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// CreateComment Creates a new pull request comment
func (client *PullRequestTag) CreateComment(user string, document string, id string, payload CommentCreate) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/pull_request/:id/comment", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return nil, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return nil, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Delete Removes a pull request
func (client *PullRequestTag) Delete(user string, document string, id string) (*Message, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/pull_request/:id", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("DELETE", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Get Returns a pull request
func (client *PullRequestTag) Get(user string, document string, id string) (*PullRequest, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document
    pathParams["id"] = id

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/pull_request/:id", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data PullRequest
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// GetAll Returns all pull requests
func (client *PullRequestTag) GetAll(user string, document string, status int, startIndex int, count int, search string) (*PullRequestCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document

    queryParams := make(map[string]interface{})
    queryParams["status"] = status
    queryParams["startIndex"] = startIndex
    queryParams["count"] = count
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/pull_request", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data PullRequestCollection
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// GetAllComments Shows all pull request comments
func (client *PullRequestTag) GetAllComments(user string, document string, id string, startIndex int, count int, search string) (*CommentCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["user"] = user
    pathParams["document"] = document
    pathParams["id"] = id

    queryParams := make(map[string]interface{})
    queryParams["startIndex"] = startIndex
    queryParams["count"] = count
    queryParams["search"] = search

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/document/:user/:document/pull_request/:id/comment", pathParams))
    if err != nil {
        return nil, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return nil, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return nil, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return nil, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data CommentCollection
        err := json.Unmarshal(respBody, &data)

        return &data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Message
        err := json.Unmarshal(respBody, &data)

        return nil, &MessageException{
            Payload: data,
            Previous: err,
        }
    }

    return nil, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewPullRequestTag(httpClient *http.Client, parser *sdkgen.Parser) *PullRequestTag {
	return &PullRequestTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
