
// resource_group automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type ResourceGroup struct {
    Prefix string `json:"prefix"`
    OperationCount int `json:"operationCount"`
}

