
// statistic automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type Statistic struct {
    OperationCount int `json:"operationCount"`
    TypeCount int `json:"typeCount"`
    AveragePropertiesPerType float64 `json:"averagePropertiesPerType"`
    TypeReusabilityIndex float64 `json:"typeReusabilityIndex"`
    MaxPathDepth int `json:"maxPathDepth"`
    AvgParamsPerOperation float64 `json:"avgParamsPerOperation"`
    ExtendedTypeCount int `json:"extendedTypeCount"`
    DiscriminatorTypeCount int `json:"discriminatorTypeCount"`
    MaxTypeNestingDepth int `json:"maxTypeNestingDepth"`
    ArgumentDistribution *ArgumentDistribution `json:"argumentDistribution"`
    MethodDistribution *MethodDistribution `json:"methodDistribution"`
    PrimitiveDistribution *PrimitiveTypeDistribution `json:"primitiveDistribution"`
    PropertyComplexity []PropertyBucket `json:"propertyComplexity"`
    TopResourceGroups []ResourceGroup `json:"topResourceGroups"`
    LargestTypes []LargestType `json:"largestTypes"`
    MostUsedProperties []NameCount `json:"mostUsedProperties"`
    MostUsedArguments []NameCount `json:"mostUsedArguments"`
}

