// tag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type Tag struct {
	Id         string    `json:"id"`
	Document   Document  `json:"document"`
	User       User      `json:"user"`
	Version    string    `json:"version"`
	Changelog  string    `json:"changelog"`
	Spec       any       `json:"spec"`
	InsertDate time.Time `json:"insertDate"`
}
