// tag_changelog automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type TagChangelog struct {
	Master    any      `json:"master"`
	Tag       any      `json:"tag"`
	Version   string   `json:"version"`
	Changelog []string `json:"changelog"`
}
