
// trigger_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type TriggerUpdate struct {
    Id int `json:"id"`
    User *User `json:"user"`
    Document *Document `json:"document"`
    Type string `json:"type"`
    Config *TriggerConfig `json:"config"`
    UpdateDate string `json:"updateDate"`
    InsertDate string `json:"insertDate"`
}

