// trigger automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

import "time"

type Trigger struct {
	Id         int           `json:"id"`
	User       User          `json:"user"`
	Document   Document      `json:"document"`
	Type       string        `json:"type"`
	Config     TriggerConfig `json:"config"`
	UpdateDate time.Time     `json:"updateDate"`
	InsertDate time.Time     `json:"insertDate"`
}
